# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Writer'), (2, 'Editor'), (3, 'Supervisor')], default=1),
        ),
    ]
