# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180705_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('author', 'title')]),
        ),
    ]
